# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_parametersForm(object):
    def setupUi(self, parametersForm):
        parametersForm.setObjectName("parametersForm")
        parametersForm.resize(425, 464)
        self.saveButton = QtWidgets.QPushButton(parametersForm)
        self.saveButton.setGeometry(QtCore.QRect(180, 420, 112, 34))
        self.saveButton.setObjectName("saveButton")
        self.exitButton = QtWidgets.QPushButton(parametersForm)
        self.exitButton.setGeometry(QtCore.QRect(300, 420, 112, 34))
        self.exitButton.setObjectName("exitButton")
        self.detectionParametersGroupBox = QtWidgets.QGroupBox(parametersForm)
        self.detectionParametersGroupBox.setGeometry(QtCore.QRect(10, 10, 251, 161))
        self.detectionParametersGroupBox.setObjectName("detectionParametersGroupBox")
        self.label_4 = QtWidgets.QLabel(self.detectionParametersGroupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 121, 19))
        self.label_4.setObjectName("label_4")
        self.blurPowerLineEdit = QtWidgets.QLineEdit(self.detectionParametersGroupBox)
        self.blurPowerLineEdit.setGeometry(QtCore.QRect(170, 90, 61, 25))
        self.blurPowerLineEdit.setText("")
        self.blurPowerLineEdit.setObjectName("blurPowerLineEdit")
        self.label = QtWidgets.QLabel(self.detectionParametersGroupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.detectionParametersGroupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.detectionParametersGroupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 121, 19))
        self.label_3.setObjectName("label_3")
        self.counterAreaLineEdit = QtWidgets.QLineEdit(self.detectionParametersGroupBox)
        self.counterAreaLineEdit.setGeometry(QtCore.QRect(170, 30, 61, 25))
        self.counterAreaLineEdit.setText("")
        self.counterAreaLineEdit.setObjectName("counterAreaLineEdit")
        self.lowThresholdLineEdit = QtWidgets.QLineEdit(self.detectionParametersGroupBox)
        self.lowThresholdLineEdit.setGeometry(QtCore.QRect(170, 120, 61, 25))
        self.lowThresholdLineEdit.setText("")
        self.lowThresholdLineEdit.setObjectName("lowThresholdLineEdit")
        self.blurSizeLineEdit = QtWidgets.QLineEdit(self.detectionParametersGroupBox)
        self.blurSizeLineEdit.setGeometry(QtCore.QRect(170, 60, 61, 25))
        self.blurSizeLineEdit.setText("")
        self.blurSizeLineEdit.setObjectName("blurSizeLineEdit")
        self.botParametersGroupBox = QtWidgets.QGroupBox(parametersForm)
        self.botParametersGroupBox.setGeometry(QtCore.QRect(10, 180, 401, 231))
        self.botParametersGroupBox.setObjectName("botParametersGroupBox")
        self.label_5 = QtWidgets.QLabel(self.botParametersGroupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 111, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.botParametersGroupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 111, 19))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.botParametersGroupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 111, 19))
        self.label_7.setObjectName("label_7")
        self.botTokenLineEdit = QtWidgets.QLineEdit(self.botParametersGroupBox)
        self.botTokenLineEdit.setGeometry(QtCore.QRect(140, 40, 241, 25))
        self.botTokenLineEdit.setObjectName("botTokenLineEdit")
        self.chatIdLineEdit = QtWidgets.QLineEdit(self.botParametersGroupBox)
        self.chatIdLineEdit.setGeometry(QtCore.QRect(140, 70, 241, 25))
        self.chatIdLineEdit.setObjectName("chatIdLineEdit")
        self.proxyUrlLineEdit = QtWidgets.QLineEdit(self.botParametersGroupBox)
        self.proxyUrlLineEdit.setGeometry(QtCore.QRect(140, 100, 241, 25))
        self.proxyUrlLineEdit.setObjectName("proxyUrlLineEdit")
        self.label_8 = QtWidgets.QLabel(self.botParametersGroupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 190, 111, 19))
        self.label_8.setObjectName("label_8")
        self.sendingPeriodLineEdit = QtWidgets.QLineEdit(self.botParametersGroupBox)
        self.sendingPeriodLineEdit.setGeometry(QtCore.QRect(140, 190, 61, 25))
        self.sendingPeriodLineEdit.setObjectName("sendingPeriodLineEdit")
        self.label_9 = QtWidgets.QLabel(self.botParametersGroupBox)
        self.label_9.setGeometry(QtCore.QRect(210, 190, 41, 19))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.botParametersGroupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 130, 111, 19))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.botParametersGroupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 160, 111, 19))
        self.label_11.setObjectName("label_11")
        self.proxyUsernameLineEdit = QtWidgets.QLineEdit(self.botParametersGroupBox)
        self.proxyUsernameLineEdit.setGeometry(QtCore.QRect(140, 130, 241, 25))
        self.proxyUsernameLineEdit.setObjectName("proxyUsernameLineEdit")
        self.proxyPasswordLineEdit = QtWidgets.QLineEdit(self.botParametersGroupBox)
        self.proxyPasswordLineEdit.setGeometry(QtCore.QRect(140, 160, 241, 25))
        self.proxyPasswordLineEdit.setObjectName("proxyPasswordLineEdit")
        self.detectionParametersGroupBox.raise_()
        self.saveButton.raise_()
        self.exitButton.raise_()
        self.botParametersGroupBox.raise_()

        self.retranslateUi(parametersForm)
        QtCore.QMetaObject.connectSlotsByName(parametersForm)

    def retranslateUi(self, parametersForm):
        _translate = QtCore.QCoreApplication.translate
        parametersForm.setWindowTitle(_translate("parametersForm", "Parameters"))
        self.saveButton.setText(_translate("parametersForm", "Save"))
        self.exitButton.setText(_translate("parametersForm", "Exit"))
        self.detectionParametersGroupBox.setTitle(_translate("parametersForm", "Detection parameters"))
        self.label_4.setText(_translate("parametersForm", "Low threshold"))
        self.label.setText(_translate("parametersForm", "Contour area size"))
        self.label_2.setText(_translate("parametersForm", "Blur size"))
        self.label_3.setText(_translate("parametersForm", "Blur power"))
        self.botParametersGroupBox.setTitle(_translate("parametersForm", "Telegram bot parameters"))
        self.label_5.setText(_translate("parametersForm", "Bot token"))
        self.label_6.setText(_translate("parametersForm", "Chat\'s id"))
        self.label_7.setText(_translate("parametersForm", "Proxy URL"))
        self.label_8.setText(_translate("parametersForm", "Sending period"))
        self.label_9.setText(_translate("parametersForm", "sec."))
        self.label_10.setText(_translate("parametersForm", "Username"))
        self.label_11.setText(_translate("parametersForm", "Password"))

